# Generated by Django 4.0.5 on 2022-06-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Нажмите на ссылку, чтобы прочитать пост', max_length=255),
        ),
    ]
